backend:
  name: github
  repo: syenelee/future-site
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "博客文章"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "标题"
        name: "title"
        widget: "string"

      - label: "发布日期"
        name: "date"
        widget: "datetime"

      - label: "正文"
        name: "body"
        widget: "markdown"